'use strict';
const $ = id => document.getElementById(id);
const statusNames = {PENDING:'待执行',RUNNING:'执行中',SUCCESS:'已完成',FAILED:'执行结束',NOT_FOUND:'未找到'};
let context, currentCleanup;
function node(tag, text, className) { const n=document.createElement(tag); if(text!==undefined)n.textContent=text; if(className)n.className=className; return n; }
function when(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString('zh-CN',{hour12:false});}
function showNotice(message,error=false){$('notice').hidden=false;$('notice').textContent=message;$('notice').classList.toggle('error',error);}
async function api(path, values){const options={credentials:'same-origin',headers:{}};if(values!==undefined){options.method='POST';options.headers={'Content-Type':'application/json','X-Tool-CSRF':context.csrf};options.body=JSON.stringify(values);}const response=await fetch(path,options);const result=await response.json();if(!result.ok)throw new Error(result.message||'操作未完成');return result.data;}
function button(text,callback,warn=false){const b=node('button',text,'link-btn'+(warn?' warn':''));b.type='button';b.addEventListener('click',callback);return b;}
async function loadTasks(){try{const data=await api('/api/tasks');$('tasks').replaceChildren();$('empty-tasks').hidden=data.records.length>0;for(const record of data.records){const row=node('tr');const p=record.payload,progress=record.progress;const title=node('td');title.append(node('span',p.keyword||'原有任务','task-title'),node('span',(p.expected_author||'—')+' · '+(p.content_type||'—'),'task-meta'),node('span',when(record.submitted_at),'task-meta'));row.append(title);const state=node('td');state.append(node('span',statusNames[record.status]||'状态异常','badge '+record.status));state.append(node('span',progress?(progress.finished_device_count+' / '+progress.target_device_count+' 台结束'):record.admitted?'等待设备分配':'已提交，待接入','progress-text'));if(record.intake_error)state.append(node('span','接入暂未完成','progress-text'));row.append(state);for(const action of ['Like','Favorite','Comment','Share'])row.append(node('td',String(progress?.counts?.[action]??0)));const actions=node('td');const wrap=node('div',undefined,'actions');wrap.append(button('详情',()=>showDetail(record.task_id)));if(record.can_cleanup)wrap.append(button('清理异常',()=>openCleanup(record),true));actions.append(wrap);row.append(actions);$('tasks').append(row);}if(data.warning)showNotice(data.warning,true);}catch(error){showNotice(error.message,true);$('empty-tasks').hidden=false;}}
async function showDetail(identity){try{const r=await api('/api/task/'+encodeURIComponent(identity));const p=r.payload;$('detail-content').replaceChildren();const grid=node('div',undefined,'detail-grid');for(const [title,value] of [['任务 ID',identity],['关键词',p.keyword],['作者昵称',p.expected_author],['抖音号',p.expected_douyin_id],['作品类型',p.content_type],['执行设备数量',p.target_device_count],['提交时间',when(r.submitted_at)],['执行时间',p.scheduled_time==='0'?'立即执行':p.scheduled_time]]){const cell=node('div');cell.append(node('span',title),node('strong',value||'—'));grid.append(cell);}$('detail-content').append(grid);if(r.intake_error)$('detail-content').append(node('pre',r.intake_error));const accounts=r.progress?.accounts||[];if(accounts.length){const table=node('table'),head=node('thead'),tr=node('tr');for(const s of ['设备 / 执行账号','结果','点赞','收藏','评论','分享'])tr.append(node('th',s));head.append(tr);table.append(head);const body=node('tbody');for(const a of accounts){const row=node('tr');const first=node('td');first.append(node('span',a.physical_device_id||'—','task-title'),node('span',a.sender_account_id,'task-meta'));row.append(first,node('td',statusNames[a.status]||a.status));for(const action of ['Like','Favorite','Comment','Share'])row.append(node('td',String(a.counts?.[action]??0)));body.append(row);if(a.error_code||a.log_message){const errorRow=node('tr'),cell=node('td');cell.colSpan=6;cell.append(node('pre',[a.error_code,a.log_message].filter(Boolean).join('\n')));errorRow.append(cell);body.append(errorRow);}}table.append(body);const wrap=node('div',undefined,'table-wrap');wrap.append(table);$('detail-content').append(wrap);}else{$('detail-content').append(node('p','尚无设备执行记录。'));}$('detail-content').append(node('p','候选评论'),node('pre',p.comments||'—'));$('detail').showModal();}catch(error){showNotice(error.message,true);}}
async function loadErrors(){try{const data=await api('/api/errors');$('errors').replaceChildren();$('empty-errors').hidden=data.errors.length>0;for(const e of data.errors){const card=node('article',undefined,'error-card');card.append(node('h3',e.task_id?'任务 '+e.task_id:(e.source||'程序错误')),node('p',[when(e.recorded_at),e.physical_device_id||e.sender_account_id,e.source].filter(Boolean).join(' · ')),node('pre',[e.error_code,e.log_message].filter(Boolean).join('\n')));$('errors').append(card);}if(data.warning)showNotice(data.warning,true);}catch(error){showNotice(error.message,true);}}
function openCleanup(record){currentCleanup=record;$('cleanup-target').textContent=(record.payload.keyword||'原有任务')+' · '+record.task_id;$('stop-row').hidden=!record.requires_stop;$('stopped').checked=false;$('cleanup-message').textContent='';$('cleanup').showModal();}
function countComments(){const form=$('task-form');const count=new Set(form.elements.comments.value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean)).size;const needed=Number(form.elements.target_device_count.value)||1;$('comment-count').textContent='有效评论 '+count+' 条，至少需要 '+needed+' 条。';}
$('task-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));values.target_device_count=Number(values.target_device_count);$('submit').disabled=true;try{const result=await api('/api/tasks',values);showNotice(result.message+'。任务 ID：'+result.task_id);form.reset();countComments();await loadTasks();}catch(error){showNotice(error.message,true);}finally{$('submit').disabled=false;}});
for(const name of ['comments','target_device_count'])$('task-form').elements[name].addEventListener('input',countComments);
$('history-tab').addEventListener('click',()=>{$('history-panel').hidden=false;$('errors-panel').hidden=true;$('history-tab').classList.add('selected');$('errors-tab').classList.remove('selected');$('workspace-title').textContent='执行记录';loadTasks();});
$('errors-tab').addEventListener('click',()=>{$('history-panel').hidden=true;$('errors-panel').hidden=false;$('errors-tab').classList.add('selected');$('history-tab').classList.remove('selected');$('workspace-title').textContent='错误记录';loadErrors();});
$('close-detail').addEventListener('click',()=>$('detail').close());for(const id of ['close-cleanup','cancel-cleanup'])$(id).addEventListener('click',()=>$('cleanup').close());
$('confirm-cleanup').addEventListener('click',async()=>{if(currentCleanup.requires_stop&&!$('stopped').checked){$('cleanup-message').textContent='请先停止 B 电脑上的影刀运行，再勾选确认。';return;}$('confirm-cleanup').disabled=true;try{const result=await api('/api/cleanup/'+encodeURIComponent(currentCleanup.task_id),{stopped:$('stopped').checked});$('cleanup').close();showNotice(result.message+(result.warning?'。'+result.warning:''));await loadTasks();if(!$('errors-panel').hidden)await loadErrors();}catch(error){$('cleanup-message').textContent=error.message;}finally{$('confirm-cleanup').disabled=false;}});
(async()=>{try{context=await api('/api/context');$('role').textContent=context.admin?'B 本机 · 管理全部任务':'本浏览器 · 仅自己的任务';$('scope').textContent=context.admin?'全部任务，按提交时间从新到旧排列。':'仅显示本浏览器提交的任务，按时间从新到旧排列。';$('access').textContent=context.lan_url;$('access').href=context.lan_url;$('version').textContent='v'+context.version;countComments();await loadTasks();}catch(error){showNotice(error.message,true);$('role').textContent='连接未完成';}})();
